In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
pd.set_option('display.width', 80)
pd.set_option('display.max_columns', 7)
pd.set_option('display.max_rows', 20)
pd.options.display.float_format = '{:,.0f}'.format
covidtotals = pd.read_pickle("data/covidtotalswithmissing.pkl")

In [2]:
# set up the cumulative and demographic columns
totvars = ['location','total_cases','total_deaths','total_cases_pm',
  'total_deaths_pm']
demovars = ['population','pop_density','median_age','gdp_per_capita',
  'hosp_beds']

In [6]:
# check the demographic columns for missing
covidtotals[demovars].isnull().sum(axis=0)
demovarsmisscnt = covidtotals[demovars].isnull().sum(axis=1)
demovarsmisscnt.value_counts()
covidtotals.loc[demovarsmisscnt>=3, ['location'] + demovars].head(5).T
#type(demovarsmisscnt)

iso_code,AND,AIA,BES,VGB,FRO
location,Andorra,Anguilla,Bonaire Sint Eustatius and Saba,British Virgin Islands,Faeroe Islands
population,"77,265","15,002","26,221","30,237","48,865"
pop_density,164,NaN,NaN,208,35
median_age,NaN,NaN,NaN,NaN,NaN
gdp_per_capita,NaN,NaN,NaN,NaN,NaN
hosp_beds,NaN,NaN,NaN,NaN,NaN

In [4]:
# check the cumulative columns for missing
covidtotals[totvars].isnull().sum(axis=0)
totvarsmisscnt = covidtotals[totvars].isnull().sum(axis=1)
totvarsmisscnt.value_counts()
covidtotals.loc[totvarsmisscnt>0].T

iso_code                         HKG
lastdate         2020-05-26 00:00:00
location                   Hong Kong
total_cases                        0
total_deaths                       0
total_cases_pm                   NaN
total_deaths_pm                  NaN
population                 7,496,988
pop_density                    7,040
median_age                        45
gdp_per_capita                56,055
hosp_beds                        NaN

In [5]:
# use the fillna method to fix the missing case data
covidtotals.total_cases_pm.fillna(covidtotals.total_cases/
  (covidtotals.population/1000000), inplace=True)
covidtotals.total_deaths_pm.fillna(covidtotals.total_deaths/
  (covidtotals.population/1000000), inplace=True)
covidtotals[totvars].isnull().sum(axis=0)

covidtotals.to_pickle("covidtotals.pkl")